# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3fd673261d0c9fb451e08661fded68b6118dd108d08c49cc796544ad897ab877d2ff7abb9367a081485f7692fa420632f19f5496f43966b31c8834d2aa5ed8b4

test:
  secret_key_base: 3d5b39d4b966aea6b1a93e9179ac0cc6de4ae797ef1c26040ef5120d5947ea0b6155b5c1309798f5cb7a25e3d86af2861ecf1a3a00e224c2fafa4610e71cc2fa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
